#:schema node_modules/wrangler/config-schema.json
name = "jlu-api"
main = "src/index.ts"
compatibility_date = "2024-11-06"
compatibility_flags = ["nodejs_compat"]

[[routes]]
pattern = "api.juicylucy.ai"
custom_domain = true

[observability]
enabled = true

[placement]
mode = "smart"

[vars]
TWITTER_CLIENT_ID = "V1pmZnRIcTJqZnNNbFNILTNnQXI6MTpjaQ"
TWITTER_LUCY_USER_ID = "1861724864756822016"
OPENAI_API_URL = "https://api.cerebras.ai"
NEAR_ACCOUNT_ID = "juicylucy.near"
JLU_TOKEN_ID = "jlu-1018.meme-cooking.near"
JLU_PER_POINT = "30000000000000000000"

[durable_objects]
bindings = [
  { name = "SESSION", class_name = "Session" },
  { name = "FLIRTBATTLE", class_name = "FlirtBattle" },
]

[[migrations]]
tag = "v1"
new_classes = ["Session", "FlirtBattle"]

[[kv_namespaces]]
binding = "KV"
id = "19f61b774756438ca781e93e120b2862"
