#:schema node_modules/wrangler/config-schema.json
name = "api"
main = "src/index.ts"
compatibility_date = "2024-11-12"

[observability]
enabled = true

[placement]
mode = "smart"

[vars]
TWITTER_CLIENT_ID = "V1pmZnRIcTJqZnNNbFNILTNnQXI6MTpjaQ"

[[durable_objects.bindings]]
name = "SESSION"
class_name = "Session"

[[migrations]]
tag = "v1"
new_classes = ["Session"]

[[kv_namespaces]]
binding = "KV"
id = "19f61b774756438ca781e93e120b2862"
