#:schema node_modules/wrangler/config-schema.json
name = "jlu-api"
main = "src/index.ts"
compatibility_date = "2024-11-06"

[observability]
enabled = true

[placement]
mode = "smart"

[vars]
TWITTER_CLIENT_ID = "VXNlckNsaWVudDpLbmxYbWxKbGJuUTZWWE5sY2tOc2FXVnVkRHBMYm14WWJXeFNiakp3YTFwMlRtdHNiVTVZVVRBPQ"
DEV = "1"

[durable_objects]
bindings = [
  { name = "SESSION", class_name = "Session" },
  { name = "FLIRTBATTLE", class_name = "FlirtBattle" },
]

[[migrations]]
tag = "v1"
new_classes = ["Session", "FlirtBattle"]

[[kv_namespaces]]
binding = "KV"
id = "19f61b774756438ca781e93e120b2862"
